### PR TITLE
move h5py into real dependencies

### PR DESCRIPTION
**Pull request by stan-dot**

### CODE REVIEW

**Comment by DiamondJoseph** [comment]
Isn't this only required for the SimPatternGenerator? Can we have it as a sim dependency and note that using the SimPatternGenerator requires it to be available?

**Comment by stan-dot** [comment]
sounds like we could do that, I am not familiar with sim dependencies however. Do tell more

**Comment by callumforrester** [comment]
@coretl said to do that before he left. 

@stan-dot, you need to make the sim dependencies. You should make a set of optional dependencies (similar to `dev`) that lists dependencies that are only required for the sim module. Then a user can type `pip install ophyd-async[sim]` to get them.

**Comment by stan-dot** [comment]
ah I see, it's not that complicated then. thanks!

**Comment by DiamondJoseph** [comment]
Would having in the pyproject.toml of your beamline plans module "ophyd-async[sim]" pick up those dependencies through any chaining? Good thing to try out.

**Comment by stan-dot** [comment]
@DiamondJoseph why wouldn't it?

**Comment by jwlodek** [comment]
I am pretty sure that is how it works. I had packages that did dev installs of dependencies before and it worked

**Comment by callumforrester** [comment]
@DiamondJoseph yes, you can have this, if that's what you're asking

```toml
dev = [
    "ophyd-async[sim]",
    ...
]

sim = [
    ...
]
```

**Review by DiamondJoseph — APPROVED** [review]

**Comment by DiamondJoseph** [comment]
> ```toml
> dev = [
>     "ophyd-async[sim]",
>     ...
> ]
> ```

I was more thinking:

dodal.dependencies = "ophyd-async"
i22_bluesky.dependencies = "dodal, ophyd-async[sim]"

**Comment by DiamondJoseph** [comment]
@stan-dot please update the branch and when merging squash and reword the commit

**Pull request merged**
