### PR TITLE
Add ADR for procedural device definition

### PR DESCRIPTION
**Pull request by coretl**
@DominicOram @callumforrester @RAYemelyanova @danielballan @mrakitin @prjemian @tacaswell I have discussed various parts of this with you at various times, and I decided to write down what we have discussed. The final iteration is that the we couldn't think of a non-magic declarative approach to nested Devices. If anyone has a good suggestion then we could revisit this ADR, otherwise I propose we merge this and stick with procedural Devices.

### CODE REVIEW

**Comment by coretl** [comment]
Fixes #9

**Review by callumforrester — APPROVED** [review]
Build needs fixing but other than that

**Review by DominicOram — APPROVED** [review]
Sounds good to me

**Comment by RAYemelyanova** [comment]
going to rebase this on top of the recent changes, then happy to approve

**Pull request merged**
