### PR TITLE
Add save load

### PR DESCRIPTION
**Pull request by coretl**
As per #27 #31 #18, but now targeted on main

### CODE REVIEW

**Comment by coretl** [comment]
@jsouter please could you rebase on main?

**Comment by jsouter** [comment]
> @jsouter please could you rebase on main?

Having some issues with this, have spoken to Ollie and he's happy for me to lose a lot of the git history and add all the device save loader logic in one or two commits on top of main with him as a co-author (if you're happy with that too), will let you know once I can fix the tests.

**Comment by coretl** [comment]
That sounds good thanks

**Comment by jsouter** [comment]
Okay, that's everything as far as I can tell, should be ready to merge/review

**Pull request merged**
