### PR TITLE
Setup PandA writer to set create directory depth PV on open

### PR DESCRIPTION
**Pull request by jwlodek**
Depends on https://github.com/PandABlocks/PandABlocks-ioc/pull/128 being merged/released.

Tested w/ a real PandA in both the success and failure cases. Resolves https://github.com/bluesky/ophyd-async/issues/317

### CODE REVIEW

**Review by evalott100 — APPROVED** [review]

**Comment by jwlodek** [comment]
@evalott100 when you have a chance, if you could make a release of the PandA IOC I will go ahead and merge this afterwards (don't want to merge until a released version of the IOC can work with this).

**Comment by evalott100** [comment]
> could make a release of the PandA IOC I will go ahead and merge this afterwards

Will do today :pray:

**Comment by evalott100** [comment]
[Released](https://github.com/PandABlocks/PandABlocks-ioc/releases/tag/0.9.0)! Merge when ready.

**Comment by jwlodek** [comment]
Thank you so much!

**Pull request merged**
